name: Deploy to QA
on:
  workflow_dispatch:
jobs:
  deploy:
    name: Install dependencies
    runs-on: ubuntu-latest
    environment:
      name: QA
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
      - name: Install dependencies
        run: npm ci --workspaces
      - name: Deploy API to QA environment
        run: |
          echo "Deploying API to QA..."
          # Add your deployment commands here, e.g., using SSH or a cloud provider CLI
      - name: Deploy web to QA environment
        run: |
          echo "Deploying web application to QA..."
          # Add your deployment commands here, e.g., using SSH or a cloud provider CLI
