name: Deploy to Staging
on:
  push:
    branches:
      - dev
jobs:
  deploy:
    name: Install dependencies
    runs-on: ubuntu-latest
    environment:
      name: Staging
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
      - name: Install dependencies
        run: npm ci --workspaces
      - name: Deploy API to Staging environment
        run: |
          echo "Deploying API to staging..."
          # Add your deployment commands here, e.g., using SSH or a cloud provider CLI
      - name: Deploy web to Staging environment
        run: |
          echo "Deploying web application to staging..."
          # Add your deployment commands here, e.g., using SSH or a cloud provider CLI
